### PR TITLE
Nit Permit() test

### PR DESCRIPTION
**Pull request by audsssy**
Context
- Nit after noticing `permit should work if the signature is valid` test throws InvalidSignature() via subtext even though it passes test (see below).. not sure why it passes in the first place

Screenshot 2022-01-07 215247

~~KaliDAOtoken.sol~~
~~- Update input parameter to `digest` in permit() as `nonces[owner]++` throws InvalidSignature()~~

KaliDAO.test.js
- Update "permit should work if the signature is valid" test logic with expect() to validate expected test result

### CODE REVIEW

**Comment by z0r0z** [comment]
good stuff @audsssy why do we think incrementing the nonce outside of digest provides fix here?

**Review by z0r0z — APPROVED** [review]
nice fixes, also appreciate expanding test to cover proposal and transferFrom

**Comment by audsssy** [comment]
**Update:**
Looks like the error was a result of unmatched function name between 

(1)
Screenshot 2022-01-08 165221

and 

(2) 
Screenshot 2022-01-08 164012

Once `PERMIT_TYPEHASH` in (1) is updated to `Permit` to match that in (2), the error goes away!

**Comment by audsssy** [comment]
**Update:**
Looks like the error was a result of unmatched function name between 

(1)
Screenshot 2022-01-08 165221

and 

(2) 
Screenshot 2022-01-08 164012

Once `PERMIT_TYPEHASH` in (1) is updated to `Permit` to match that in (2), the error goes away!

**Comment by audsssy** [comment]
Woot. Thanks for the review and merge!

**Pull request merged**
