### PR TITLE
Refactor factory form

### PR DESCRIPTION
**Pull request by nerderlyne**

### CODE REVIEW

**Comment by nerderlyne** [comment]
coool so I think this is somehow breaking "Deployed DAOs" and I also wasn't able to deploy a DAO from the form so that might require some changes. Will make and mergeeee

**Comment by z0r0z** [comment]
great @nerderlyne 
so I think we can start integrating the new factory params by doing the following:
- empty presets for `extensions`, `extensionsData` and `govSettings` arrays (this last one will set everything to simple majority)

**Comment by nerderlyne** [comment]
Looking at the smart contracts, `govSettings` array should follow this structure: 
```
quorum = govSettings_[0];
        
supermajority = govSettings_[1];

// set initial vote types
proposalVoteTypes[ProposalType.MINT] = VoteType(govSettings_[2]);

proposalVoteTypes[ProposalType.BURN] = VoteType(govSettings_[3]);

proposalVoteTypes[ProposalType.CALL] = VoteType(govSettings_[4]);

proposalVoteTypes[ProposalType.PERIOD] = VoteType(govSettings_[5]);

proposalVoteTypes[ProposalType.QUORUM] = VoteType(govSettings_[6]);

proposalVoteTypes[ProposalType.SUPERMAJORITY] = VoteType(govSettings_[7]);

proposalVoteTypes[ProposalType.TYPE] = VoteType(govSettings_[8]);

proposalVoteTypes[ProposalType.PAUSE] = VoteType(govSettings_[9]);

proposalVoteTypes[ProposalType.EXTENSION] = VoteType(govSettings_[10]);

proposalVoteTypes[ProposalType.DOCS] = VoteType(govSettings_[11]);
```

I see that you put `(0, 0, 0, 0, 0, 0, 0, 0, 0, 0)` as the initialValue on UI(one more zero here? lol)

**Comment by nerderlyne** [comment]
so I made some edits and now the form does submit but its reverted by the EVM

I think this is because I am not giving the right input for extensionsData or extensions(i have never done this kind of tx so dunno what to put in there) 

the values for this are hardcoded for now so make those changes and it should work imo 

@Ro5s

**Comment by z0r0z** [comment]
awesome thanks @nerderlyne 
I think I know the issue (I used null address for extensionData bytes.... which might not play nice)
I'll take a look and make nits. Appreciate quick fixes here.

**Comment by z0r0z** [comment]
I think I found the culprit :~) Some of the presets were hitting the bound requirements we have in constructor https://rinkeby.etherscan.io/tx/0x31cdbdb9a6535b3e65c3a51d8216afbc31add214e6af6c54d6865198dd4edf3f

**Comment by nerderlyne** [comment]
this made a lot of sense thx 

it is stitched!

**Pull request merged**
